services:
  fastapi:
    build: ./backend/
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - OTEL_JAEGER_TRACE_PORT=4318
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp" # Needed for .. Thrift?
      - "5778:5778" # Configs
      - "16686:16686" # UI
      - "14250:14250" # Needed for .. Proto?
      - "14268:14268" # Needed for .. Thrift?
      - "4318:4318" # HTTP OTEL Protocol Port
